<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE projet [
	<!ELEMENT projet (infos, pseudocode, tableau, graph) >
	<!ATTLIST projet diapos CDATA #REQUIRED >

	<!ELEMENT infos (auteur, titre, titreCourt, sousTitre, algo, institut, date, sizes, couleurs) >
	<!ELEMENT auteur (#PCDATA) >
	<!ELEMENT titre (#PCDATA) >
	<!ELEMENT titreCourt (#PCDATA) >
	<!ELEMENT sousTitre (#PCDATA) >
	<!ELEMENT algo (#PCDATA) >
	<!ELEMENT institut (#PCDATA) >
	<!ELEMENT date (#PCDATA) >
	<!ELEMENT sizes (hspaceCodeTab, codeSize, tabSize) >
	<!ELEMENT hspaceCodeTab EMPTY >
	<!ATTLIST hspaceCodeTab value CDATA #REQUIRED >
	<!ELEMENT codeSize EMPTY >
	<!ATTLIST codeSize value CDATA #REQUIRED >
	<!ELEMENT tabSize EMPTY >
	<!ATTLIST tabSize value CDATA #REQUIRED >
	<!ELEMENT couleurs (couleurNoeudInitial, couleursNoeuds, couleursLiens) >
	<!ELEMENT couleurNoeudInitial EMPTY >
	<!ATTLIST couleurNoeudInitial r CDATA #REQUIRED >
	<!ATTLIST couleurNoeudInitial g CDATA #REQUIRED >
	<!ATTLIST couleurNoeudInitial b CDATA #REQUIRED >
	<!ELEMENT couleursNoeuds (couleur)* >
	<!ELEMENT couleursLiens (couleur)* >
	<!ELEMENT couleur EMPTY >
	<!ATTLIST couleur etat CDATA #REQUIRED >
	<!ATTLIST couleur r CDATA #REQUIRED >
	<!ATTLIST couleur g CDATA #REQUIRED >
	<!ATTLIST couleur b CDATA #REQUIRED >

	<!ELEMENT pseudocode (texte, marqueurs) >
	<!ELEMENT texte (ligne_p)* >
	<!ELEMENT ligne_p (#PCDATA) >
	<!ELEMENT marqueurs (diapo_p)+ >
	<!ELEMENT diapo_p (marqueur)* >
	<!ATTLIST diapo_p numero CDATA #REQUIRED >
	<!ELEMENT marqueur (#PCDATA) >

	<!ELEMENT tableau (colonnes, diapos_t) >
	<!ATTLIST tableau lignes CDATA #REQUIRED >
	<!ATTLIST tableau colonnes CDATA #REQUIRED >
	<!ELEMENT colonnes (colonne)+ >
	<!ELEMENT colonne (#PCDATA) >
	<!ATTLIST colonne numero CDATA #REQUIRED >
	<!ELEMENT diapos_t (diapo_t)+ >
	<!ELEMENT diapo_t (ligne_t)+ >
	<!ATTLIST diapo_t numero CDATA #REQUIRED >
	<!ELEMENT ligne_t (case)* >
	<!ATTLIST ligne_t numero CDATA #REQUIRED >
	<!ELEMENT case (#PCDATA) >
	<!ATTLIST case numero CDATA #REQUIRED >

	<!ELEMENT graph (noeuds, liens) >
	<!ATTLIST graph styleLien (0|1) "0" >
	<!ATTLIST graph noeudInitial CDATA #REQUIRED >
	<!ELEMENT noeuds (noeud)* >
	<!ELEMENT noeud (label,etats) >
	<!ELEMENT label (#PCDATA) >
	<!ELEMENT etats (diapo_g)+ >
	<!ELEMENT diapo_g (#PCDATA) >
	<!ATTLIST diapo_g numero CDATA #REQUIRED >
	<!ATTLIST noeud x CDATA #REQUIRED >
	<!ATTLIST noeud y CDATA #REQUIRED >
	<!ATTLIST noeud id CDATA #REQUIRED >
	<!ATTLIST noeud forme (0|1) "0" >
	<!ELEMENT liens (lien)* >
	<!ELEMENT lien (label,etats) >
	<!ATTLIST lien depart CDATA #REQUIRED >
	<!ATTLIST lien arrive CDATA #REQUIRED >
]>
<projet diapos="40">

	<infos>
		<auteur>F. Bouquet</auteur>
		<titre>MOIA - Parcours en largeur</titre>
		<titreCourt>MOIA - Parcours larg.</titreCourt>
		<sousTitre>Parcours larg.</sousTitre>
		<algo>Algorithme Largeur(List,Sol)</algo>
		<institut>UFRST</institut>
		<date>Master 1re année</date>
		<sizes>
			<hspaceCodeTab value="1.0" />
			<codeSize value="5.0" />
			<tabSize value="5.0" />
		</sizes>
		<couleurs>
			<couleurNoeudInitial r="255" g="204" b="102" />
			<couleursNoeuds>
				<couleur etat="0" r="192" g="192" b="192"/>
				<couleur etat="2" r="255" g="0" b="0"/>
				<couleur etat="1" r="0" g="0" b="0"/>
				<couleur etat="3" r="0" g="255" b="0"/>
				<couleur etat="4" r="255" g="0" b="255"/>
				<couleur etat="-1" r="0" g="0" b="255"/>
			</couleursNoeuds>
			<couleursLiens>
				<couleur etat="0" r="192" g="192" b="192"/>
				<couleur etat="2" r="255" g="0" b="0"/>
				<couleur etat="1" r="0" g="0" b="0"/>
				<couleur etat="3" r="0" g="255" b="0"/>
				<couleur etat="4" r="255" g="0" b="255"/>
				<couleur etat="-1" r="0" g="0" b="255"/>
			</couleursLiens>
		</couleurs>
	</infos>

	<pseudocode>
		<texte>
			<ligne_p><![CDATA[Ch <- Premier(Liste); ﬁn <- Faux;]]></ligne_p>
			<ligne_p><![CDATA[while Ch != {} et non(ﬁn) do	]]></ligne_p>
			<ligne_p><![CDATA[   Liste <-  Liste / {Ch}; n <- dernierNoeud(Ch);]]></ligne_p>
			<ligne_p><![CDATA[   n1  <- successeur(n);]]></ligne_p>
			<ligne_p><![CDATA[   while non(ﬁn) et n1 est valide do]]></ligne_p>
			<ligne_p><![CDATA[      if n1 est solution then]]></ligne_p>
			<ligne_p><![CDATA[         Sol Ch Uf {n1}; ﬁn <- Vrai;]]></ligne_p>
			<ligne_p><![CDATA[      else Liste <- Liste Uf {(Ch Uf {n1})};]]></ligne_p>
			<ligne_p><![CDATA[      n1 <- successeur(n);]]></ligne_p>
			<ligne_p><![CDATA[   Ch Premier(Liste);]]></ligne_p>
			<ligne_p><![CDATA[return ﬁn;]]></ligne_p>
		</texte>
		<marqueurs>
			<diapo_p numero="1">
			</diapo_p>
			<diapo_p numero="2">
				<marqueur>1</marqueur>
			</diapo_p>
			<diapo_p numero="3">
				<marqueur>2</marqueur>
			</diapo_p>
			<diapo_p numero="4">
				<marqueur>3</marqueur>
			</diapo_p>
			<diapo_p numero="5">
				<marqueur>4</marqueur>
			</diapo_p>
			<diapo_p numero="6">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="7">
				<marqueur>6</marqueur>
			</diapo_p>
			<diapo_p numero="8">
				<marqueur>8</marqueur>
			</diapo_p>
			<diapo_p numero="9">
				<marqueur>9</marqueur>
			</diapo_p>
			<diapo_p numero="10">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="11">
				<marqueur>6</marqueur>
			</diapo_p>
			<diapo_p numero="12">
				<marqueur>8</marqueur>
			</diapo_p>
			<diapo_p numero="13">
				<marqueur>9</marqueur>
			</diapo_p>
			<diapo_p numero="14">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="15">
				<marqueur>10</marqueur>
			</diapo_p>
			<diapo_p numero="16">
				<marqueur>2</marqueur>
			</diapo_p>
			<diapo_p numero="17">
				<marqueur>3</marqueur>
			</diapo_p>
			<diapo_p numero="18">
				<marqueur>4</marqueur>
			</diapo_p>
			<diapo_p numero="19">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="20">
				<marqueur>6</marqueur>
			</diapo_p>
			<diapo_p numero="21">
				<marqueur>8</marqueur>
			</diapo_p>
			<diapo_p numero="22">
				<marqueur>9</marqueur>
			</diapo_p>
			<diapo_p numero="23">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="24">
				<marqueur>6</marqueur>
			</diapo_p>
			<diapo_p numero="25">
				<marqueur>8</marqueur>
			</diapo_p>
			<diapo_p numero="26">
				<marqueur>9</marqueur>
			</diapo_p>
			<diapo_p numero="27">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="28">
				<marqueur>10</marqueur>
			</diapo_p>
			<diapo_p numero="29">
				<marqueur>2</marqueur>
			</diapo_p>
			<diapo_p numero="30">
				<marqueur>3</marqueur>
			</diapo_p>
			<diapo_p numero="31">
				<marqueur>4</marqueur>
			</diapo_p>
			<diapo_p numero="32">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="33">
				<marqueur>6</marqueur>
			</diapo_p>
			<diapo_p numero="34">
				<marqueur>7</marqueur>
			</diapo_p>
			<diapo_p numero="35">
				<marqueur>9</marqueur>
			</diapo_p>
			<diapo_p numero="36">
				<marqueur>5</marqueur>
			</diapo_p>
			<diapo_p numero="37">
				<marqueur>10</marqueur>
			</diapo_p>
			<diapo_p numero="38">
				<marqueur>2</marqueur>
			</diapo_p>
			<diapo_p numero="39">
				<marqueur>11</marqueur>
			</diapo_p>
			<diapo_p numero="40">
			</diapo_p>
		</marqueurs>
	</pseudocode>

	<tableau lignes="4" colonnes="6">
		<colonnes>
			<colonne numero="0"><![CDATA[Ch]]></colonne>
			<colonne numero="1"><![CDATA[n]]></colonne>
			<colonne numero="2"><![CDATA[n1]]></colonne>
			<colonne numero="3"><![CDATA[fin]]></colonne>
			<colonne numero="4"><![CDATA[Liste]]></colonne>
			<colonne numero="5"><![CDATA[Sol]]></colonne>
		</colonnes>
		<diapos_t>
			<diapo_t numero="1">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[-]]></case>
					<case numero="1"><![CDATA[-]]></case>
					<case numero="2"><![CDATA[-]]></case>
					<case numero="3"><![CDATA[-]]></case>
					<case numero="4"><![CDATA[{{A}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="2">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[-]]></case>
					<case numero="2"><![CDATA[-]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{A}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="3">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[-]]></case>
					<case numero="2"><![CDATA[-]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{A}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="4">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[-]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="5">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[B]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="6">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[B]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="7">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[B]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="8">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[B]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="9">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[C]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="10">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[C]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="11">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[C]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="12">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[C]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="13">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="14">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="15">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="16">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="17">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="4"><![CDATA[{AC}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="18">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[D]]></case>
					<case numero="4"><![CDATA[{AC}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="19">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[D]]></case>
					<case numero="4"><![CDATA[{AC}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="20">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[D]]></case>
					<case numero="4"><![CDATA[{AC}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="21">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[D]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="22">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[E]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="23">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[E]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="24">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[E]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="25">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[E]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="26">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="27">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="28">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="29">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="30">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="31">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[F]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="32">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[F]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="33">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[F]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="34">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[F]]></case>
					<case numero="3"><![CDATA[Vrai]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
					<case numero="5"><![CDATA[{A,C,F}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="35">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[G]]></case>
					<case numero="3"><![CDATA[Vrai]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
					<case numero="5"><![CDATA[{A,C,F}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="36">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[G]]></case>
					<case numero="3"><![CDATA[Vrai]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
					<case numero="5"><![CDATA[{A,C,F}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="37">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[G]]></case>
					<case numero="3"><![CDATA[Vrai]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
					<case numero="5"><![CDATA[{A,C,F}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="38">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[G]]></case>
					<case numero="3"><![CDATA[Vrai]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
					<case numero="5"><![CDATA[{A,C,F}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="39">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[{AB}]]></case>
					<case numero="1"><![CDATA[B]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="4"><![CDATA[{{AC},{ABD},{ABE}}]]></case>
				</ligne_t>
				<ligne_t numero="3">
					<case numero="0"><![CDATA[{AC}]]></case>
					<case numero="1"><![CDATA[C]]></case>
					<case numero="2"><![CDATA[G]]></case>
					<case numero="3"><![CDATA[Vrai]]></case>
					<case numero="4"><![CDATA[{{ABD},{ABE}}]]></case>
					<case numero="5"><![CDATA[{A,C,F}]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="40">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[{A}]]></case>
					<case numero="1"><![CDATA[A]]></case>
					<case numero="2"><![CDATA[$\perp$]]></case>
					<case numero="3"><![CDATA[Faux]]></case>
					<case numero="4"><![CDATA[{{AB},{AC}}]]></case>