<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE projet [
	<!ELEMENT projet (pseudocode, tableau, graph) >
	<!ATTLIST projet diapos CDATA #REQUIRED >

	<!ELEMENT pseudocode (texte, marqueurs) >
	<!ELEMENT texte (ligne_p)* >
	<!ELEMENT ligne_p (#PCDATA) >
	<!ELEMENT marqueurs (diapo_p)+ >
	<!ELEMENT diapo_p (marqueur)* >
	<!ATTLIST diapo_p numero CDATA #REQUIRED >
	<!ELEMENT marqueur (#PCDATA) >

	<!ELEMENT tableau (colonnes, diapos_t) >
	<!ATTLIST tableau lignes CDATA #REQUIRED >
	<!ATTLIST tableau colonnes CDATA #REQUIRED >
	<!ELEMENT colonnes (colonne)+ >
	<!ELEMENT colonne (#PCDATA) >
	<!ATTLIST colonne numero CDATA #REQUIRED >
	<!ELEMENT diapos_t (diapo_t)+ >
	<!ELEMENT diapo_t (ligne_t)+ >
	<!ATTLIST diapo_t numero CDATA #REQUIRED >
	<!ELEMENT ligne_t (case)* >
	<!ATTLIST ligne_t numero CDATA #REQUIRED >
	<!ELEMENT case (#PCDATA) >
	<!ATTLIST case numero CDATA #REQUIRED >

	<!ELEMENT graph (noeuds, liens) >
	<!ELEMENT noeuds (noeud)* >
	<!ELEMENT noeud (#PCDATA) >
	<!ATTLIST noeud x CDATA #REQUIRED >
	<!ATTLIST noeud y CDATA #REQUIRED >
	<!ELEMENT liens (lien)* >
	<!ELEMENT lien (#PCDATA) >
	<!ATTLIST lien depart CDATA #REQUIRED >
	<!ATTLIST lien arrive CDATA #REQUIRED >
]>
<projet diapos="5">
	<pseudocode>
		<texte>
			<ligne_p><![CDATA[diapo1 2 5;]]></ligne_p>
			<ligne_p><![CDATA[diapo 3;]]></ligne_p>
			<ligne_p><![CDATA[diapo 4 5;]]></ligne_p>
		</texte>
		<marqueurs>
			<diapo_p numero="1">
				<marqueur>1</marqueur>
			</diapo_p>
			<diapo_p numero="2">
				<marqueur>1</marqueur>
			</diapo_p>
			<diapo_p numero="3">
				<marqueur>2</marqueur>
			</diapo_p>
			<diapo_p numero="4">
				<marqueur>3</marqueur>
			</diapo_p>
			<diapo_p numero="5">
				<marqueur>1</marqueur>
				<marqueur>3</marqueur>
			</diapo_p>
		</marqueurs>
	</pseudocode>

	<tableau lignes="3" colonnes="4">
		<colonnes>
			<colonne numero="0"><![CDATA[A]]></colonne>
			<colonne numero="1"><![CDATA[B]]></colonne>
			<colonne numero="2"><![CDATA[C]]></colonne>
			<colonne numero="3"><![CDATA[D]]></colonne>
		</colonnes>
		<diapos_t>
			<diapo_t numero="1">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[diapo 1]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="2">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[diapo 1]]></case>
					<case numero="1"><![CDATA[diapo 2]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="3">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[diapo 1]]></case>
					<case numero="1"><![CDATA[diapo 2]]></case>
					<case numero="2"><![CDATA[diapo 3]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="4">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[diapo 1]]></case>
					<case numero="1"><![CDATA[diapo 2]]></case>
					<case numero="2"><![CDATA[diapo 3]]></case>
					<case numero="3"><![CDATA[diapo 4]]></case>
				</ligne_t>
				<ligne_t numero="2">
				</ligne_t>
			</diapo_t>
			<diapo_t numero="5">
				<ligne_t numero="1">
					<case numero="0"><![CDATA[diapo 1]]></case>
					<case numero="1"><![CDATA[diapo 2]]></case>
					<case numero="2"><![CDATA[diapo 3]]></case>
					<case numero="3"><![CDATA[diapo 4]]></case>
				</ligne_t>
				<ligne_t numero="2">
					<case numero="0"><![CDATA[diapo 5]]></case>
					<case numero="1"><![CDATA[(\bold{test})]]></case>
					<case numero="2"><![CDATA[\\premier]]></case>
					<case numero="3"><![CDATA[<br>]]></case>
				</ligne_t>
			</diapo_t>
		</diapos_t>
	</tableau>

	<graph>
		<noeuds>
			<noeud x="259" y="51"><![CDATA[0]]></noeud>
			<noeud x="372" y="133"><![CDATA[1]]></noeud>
			<noeud x="496" y="63"><![CDATA[0]]></noeud>
		</noeuds>
		<liens>
			<lien depart="1" arrive="0"><![CDATA[a]]></lien>
			<lien depart="0" arrive="2"><![CDATA[test]]></lien>
			<lien depart="1" arrive="2"><![CDATA[a]]></lien>
		</liens>
	</graph>
</projet>