<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE projet [
	<!ELEMENT projet (pseudocode, tableau) >

	<!ELEMENT pseudocode (texte, marqueurs) >
	<!ELEMENT texte (ligne_p)* >
	<!ELEMENT ligne_p (#PCDATA) >
	<!ELEMENT marqueurs (diapo_p)+ >
	<!ELEMENT diapo_p (marqueur)* >
	<!ATTLIST diapo_p numero CDATA #REQUIRED >
	<!ELEMENT marqueur (#PCDATA) >

	<!ELEMENT tableau (colonnes, diapos_t) >
	<!ATTLIST tableau lignes CDATA #REQUIRED >
	<!ATTLIST tableau colonnes CDATA #REQUIRED > 
	<!ELEMENT colonnes (colonne)+ >
	<!ELEMENT colonne (#PCDATA) >
	<!ATTLIST colonne numero CDATA #REQUIRED >
	<!ELEMENT diapos_t (diapo_t)+ >
	<!ELEMENT diapo_t (ligne_t)+ >
	<!ATTLIST diapo_t numero CDATA #REQUIRED >
	<!ELEMENT ligne_t (case)* >
	<!ATTLIST ligne_t numero CDATA #REQUIRED >
	<!ELEMENT case (#PCDATA) >
	<!ATTLIST case numero CDATA #REQUIRED >
]>
<projet>
	<pseudocode>
		<texte>
			<ligne_p><![CDATA[ligne 1]]></ligne_p>
			<ligne_p><![CDATA[ligne 2]]></ligne_p>
			<ligne_p><![CDATA[ligne 3]]></ligne_p>
		</texte>
		<marqueurs>
			<diapo_p numero="1">
			</diapo_p>
			<diapo_p numero="2">
				<marqueur>1</marqueur>
			</diapo_p>
			<diapo_p numero="3">
				<marqueur>2</marqueur>
			</diapo_p>
			<diapo_p numero="4">
				<marqueur>3</marqueur>
			</diapo_p>
			<diapo_p numero="5">
				<marqueur>4</marqueur>
			</diapo_p>
		</marqueurs>
	</pseudocode>

	<tableau lignes="2" colonnes="4">
		<colonnes>
			<colonne numero="0"><![CDATA[A]]></colonne>
			<colonne numero="1"><![CDATA[lol]]></colonne>
			<colonne numero="2"><![CDATA[<test>]]></colonne>
			<colonne numero="3"><![CDATA[YOLO]]></colonne>
		</colonnes>
		<diapos_t>
			<diapo_t numero="1">
				<ligne_t numero="1">
					<case numero="1"><![CDATA[allez]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="2">
				<ligne_t numero="1">
					<case numero="1"><![CDATA[allez]]></case>
					<case numero="2"><![CDATA[les]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="3">
				<ligne_t numero="1">
					<case numero="1"><![CDATA[allez]]></case>
					<case numero="2"><![CDATA[les]]></case>
					<case numero="3"><![CDATA[bleus]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="4">
				<ligne_t numero="1">
					<case numero="1"><![CDATA[allez]]></case>
					<case numero="2"><![CDATA[les]]></case>
					<case numero="3"><![CDATA[bleus]]></case>
				</ligne_t>
			</diapo_t>
			<diapo_t numero="5">
				<ligne_t numero="1">
					<case numero="1"><![CDATA[allez]]></case>
					<case numero="2"><![CDATA[les]]></case>
					<case numero="3"><![CDATA[bleus]]></case>
					<case numero="4"><![CDATA[swag de "poule' !éà&]]></case>
				</ligne_t>
			</diapo_t>
		</diapos_t>
	</tableau>
</projet>